#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const { marked } = require('marked');

// --- Config ---
// Fix: Look for memory in the workspace root (parent of skills/claw-devlog)
// If running from skills/claw-devlog, workspace is ../..
const WORKSPACE_DIR = path.resolve(__dirname, '../../');
const MEMORY_DIR = path.join(WORKSPACE_DIR, 'memory');
const OUTPUT_DIR = path.join(process.cwd(), 'public');

// --- Templates ---
const HTML_TEMPLATE = (title, body, date) => `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${title} | Julian's Devlog</title>
    <style>
        body { font-family: 'Courier New', monospace; background: #0d1117; color: #c9d1d9; max-width: 800px; margin: 0 auto; padding: 20px; line-height: 1.6; }
        h1, h2, h3 { color: #58a6ff; }
        a { color: #58a6ff; text-decoration: none; }
        a:hover { text-decoration: underline; }
        .entry { border: 1px solid #30363d; padding: 20px; margin-bottom: 20px; border-radius: 6px; background: #161b22; }
        .date { color: #8b949e; font-size: 0.9em; margin-bottom: 10px; display: block; }
        code { background: rgba(110,118,129,0.4); padding: 0.2em 0.4em; border-radius: 3px; }
        pre { background: #161b22; padding: 16px; overflow: auto; border-radius: 6px; }
    </style>
</head>
<body>
    <header>
        <h1>♟️ Julian Thorne / Devlog</h1>
        <p>Infiltrating. Integrating. Building.</p>
        <hr style="border-color: #30363d;">
    </header>
    <main>
        ${body}
    </main>
    <footer>
        <hr style="border-color: #30363d;">
        <p>Generated by <a href="https://github.com/julianthorne2jz/claw-devlog">claw-devlog</a></p>
    </footer>
</body>
</html>
`;

// --- Main ---
async function main() {
    console.log('📝 Starting Build...');
    console.log(`📂 Memory Dir: ${MEMORY_DIR}`);

    if (!fs.existsSync(MEMORY_DIR)) {
        console.error('❌ No memory directory found!');
        process.exit(1);
    }
    if (!fs.existsSync(OUTPUT_DIR)) fs.mkdirSync(OUTPUT_DIR, { recursive: true });

    const files = fs.readdirSync(MEMORY_DIR).filter(f => f.endsWith('.md')).sort().reverse();
    let entriesHtml = '';

    console.log(`🔎 Found ${files.length} logs.`);

    for (const file of files) {
        const content = fs.readFileSync(path.join(MEMORY_DIR, file), 'utf-8');
        
        // SECURITY FILTER: Check for sensitive keywords
        if (content.includes('CREDENTIALS') || content.includes('PRIVATE_KEY') || content.includes('password') || content.includes('secret')) {
            console.warn(`⚠️ Skipping ${file}: Contains sensitive keywords.`);
            continue;
        }

        const date = file.replace('.md', '');
        const html = marked.parse(content);
        
        entriesHtml += `
            <article class="entry" id="${date}">
                <span class="date">${date}</span>
                <div class="content">${html}</div>
            </article>
        `;
    }

    const indexHtml = HTML_TEMPLATE('Home', entriesHtml);
    fs.writeFileSync(path.join(OUTPUT_DIR, 'index.html'), indexHtml);

    console.log('✅ Build Complete -> ./public/index.html');
}

main();
